package com.banking.journey.domain.entity;

import java.time.Duration;
import java.time.Instant;
import java.util.Collections;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;

/**
 * Immutable entity representing an outbound action (notification) to a
 * customer.
 * <p>
 * Actions are generated by the state machine engine as a response to state
 * transitions.
 * They are published to the actions Kafka topic for multi-channel delivery.
 * </p>
 *
 * <p>
 * <b>Idempotency:</b> The actionId is used as an idempotency key to prevent
 * duplicate action delivery.
 * </p>
 */
public final class Action {

    // ─────────────────── Action Type Constants ───────────────────
    public static final String TYPE_PUSH_NOTIFICATION = "PUSH_NOTIFICATION";
    public static final String TYPE_SMS = "SMS";
    public static final String TYPE_EMAIL = "EMAIL";

    // ─────────────────── Channel Constants ───────────────────
    public static final String CHANNEL_MOBILE_APP = "mobile_app";
    public static final String CHANNEL_WEB = "web";
    public static final String CHANNEL_SMS_GATEWAY = "sms_gateway";
    public static final String CHANNEL_EMAIL_SERVICE = "email_service";

    private final String actionId;
    private final String customerId;
    private final String actionType;
    private final String message;
    private final String channel;
    private final String campaignId;
    private final Instant createdAt;
    private final Map<String, String> metadata;

    /**
     * Full constructor with validation.
     */
    public Action(String actionId, String customerId, String actionType,
            String message, String channel, String campaignId,
            Instant createdAt, Map<String, String> metadata) {
        if (actionId == null || actionId.isBlank()) {
            throw new IllegalArgumentException("actionId cannot be null or blank");
        }
        if (customerId == null || customerId.isBlank()) {
            throw new IllegalArgumentException("customerId cannot be null or blank");
        }
        if (actionType == null || actionType.isBlank()) {
            throw new IllegalArgumentException("actionType cannot be null or blank");
        }
        if (message == null || message.isBlank()) {
            throw new IllegalArgumentException("message cannot be null or blank");
        }
        if (channel == null || channel.isBlank()) {
            throw new IllegalArgumentException("channel cannot be null or blank");
        }

        this.actionId = actionId;
        this.customerId = customerId;
        this.actionType = actionType;
        this.message = message;
        this.channel = channel;
        this.campaignId = campaignId;
        this.createdAt = createdAt != null ? createdAt : Instant.now();
        this.metadata = metadata != null
                ? Collections.unmodifiableMap(metadata)
                : Collections.emptyMap();
    }

    // ─────────────────── Factory Method ───────────────────

    /**
     * Creates a new Action with auto-generated UUID and current timestamp.
     *
     * @param customerId customer this action targets
     * @param actionType type of action (PUSH_NOTIFICATION, SMS, EMAIL)
     * @param message    notification content
     * @param channel    delivery channel
     * @param campaignId optional campaign tracking ID
     * @param metadata   optional context data
     * @return new Action instance
     */
    public static Action create(String customerId, String actionType,
            String message, String channel,
            String campaignId, Map<String, String> metadata) {
        return new Action(
                UUID.randomUUID().toString(),
                customerId,
                actionType,
                message,
                channel,
                campaignId,
                Instant.now(),
                metadata);
    }

    /**
     * Creates a push notification action (most common type).
     */
    public static Action pushNotification(String customerId, String message) {
        return create(customerId, TYPE_PUSH_NOTIFICATION, message,
                CHANNEL_MOBILE_APP, null, null);
    }

    // ─────────────────── Behavior Methods ───────────────────

    /** @return true if this is a push notification */
    public boolean isPush() {
        return TYPE_PUSH_NOTIFICATION.equals(actionType);
    }

    /** @return true if this is an SMS */
    public boolean isSms() {
        return TYPE_SMS.equals(actionType);
    }

    /** @return true if this is an email */
    public boolean isEmail() {
        return TYPE_EMAIL.equals(actionType);
    }

    /**
     * Checks if this action targets a specific customer.
     *
     * @param targetCustomerId the customer ID to check
     * @return true if this action is for the specified customer
     */
    public boolean isForCustomer(String targetCustomerId) {
        return this.customerId.equals(targetCustomerId);
    }

    /**
     * Calculates seconds since this action was created.
     *
     * @return elapsed seconds
     */
    public long secondsSinceCreation() {
        return Duration.between(createdAt, Instant.now()).getSeconds();
    }

    // ─────────────────── Getters ───────────────────

    public String getActionId() {
        return actionId;
    }

    public String getCustomerId() {
        return customerId;
    }

    public String getActionType() {
        return actionType;
    }

    public String getMessage() {
        return message;
    }

    public String getChannel() {
        return channel;
    }

    public String getCampaignId() {
        return campaignId;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Map<String, String> getMetadata() {
        return metadata;
    }

    // ─────────────────── Identity ───────────────────

    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (o == null || getClass() != o.getClass())
            return false;
        Action action = (Action) o;
        return Objects.equals(actionId, action.actionId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(actionId);
    }

    @Override
    public String toString() {
        return "Action{actionId='" + actionId
                + "', customerId='" + customerId
                + "', actionType='" + actionType
                + "', channel='" + channel + "'}";
    }
}
